enableGlobalCache: true

httpRetry: 10

httpTimeout: 600000

networkConcurrency: 1

nodeLinker: node-modules

npmMinimalAgeGate: 3d

npmPreapprovedPackages:
  - "@backstage/*"

npmRegistryServer: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-4.13.0.cjs
